# Generated by Django 5.2.15 on 2026-06-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('icon', models.CharField(blank=True, choices=[('fa-linux', 'Linux'), ('fa-windows ', 'Windows'), ('fa-apple', 'Apple'), ('fa-firefox', 'Firefox'), ('fa-chrome ', 'Chrome'), ('fa-internet-explorer', 'Internet Explorer'), ('fa-file', 'Physical File'), ('fa-file-o', 'Virtual File'), ('fa-folder', 'Folder'), ('fa-folder-o', 'Folder White')], max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('rank',),
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('rank', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, max_length=512, null=True, unique=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('usage', models.TextField(blank=True, null=True, unique=True)),
                ('code', models.TextField(blank=True, null=True, unique=True)),
                ('example', models.TextField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('categories', models.ManyToManyField(blank=True, related_name='snippets', to='snippets.category')),
                ('snippets', models.ManyToManyField(blank=True, related_name='parent', to='snippets.snippet')),
            ],
            options={
                'ordering': ('rank',),
            },
        ),
    ]
